### ISSUE TITLE
Changing init args for MODBUSClient(object) 

### ISSUE THREAD

**Issue by RonanHiggins** [ccatp/MODBUS#6]
2 smalls changes to the modbus client would help make an adaptable setup during upcoming on-site FATs (glycol system, generators, electrical equipment)

Right now the MODBUSClient class takes the device name and a path to config files. It would be better to make this more generic and take an IP address and a dictionary as an input.
The dictionary can be read from the config file or generated in a python script. The IP address should not be in the config file but passed into the class as an input. Example of MODBUSClient would be something like this:

~~~ python 
file_config = "mb_client_config_HLX.json"
client_config = json.load(config_file)
IP="127.0.0.1"
class MODBUSClient(object):
    def __init__(self,
                 IP: str = "127.0.0.1",
                 config: dict = {}):

~~~

https://github.com/ccatp/MODBUS/blob/736df289ed0fe9e7eca68d68120aa6e05c740975/modbusClient/src/mb_client_v2.py#L554

**Comment by RonanHiggins** [comment]
@nolta @Tamburasca comments welcome.

**Comment by Tamburasca** [comment]
Quick comment here: the client was never meant to be installed locally in the first instance, due to lacking requirements. It was meant to be inquired primarily by the HK. The writer could be serviced via Rest API though OCS.

**Comment by RonanHiggins** [comment]
You have to consider the FAT use case (berg, generator), the person on site will have to adapt the config file, we don't want to have to spin up the OCS for these on site tests. We need to be flexible and have the ability to change IP, config files on the fly. How will your system handle multiple units (16 compressor IPs for example), will we have a config file for each unit? The config file name for each system is statically written in the code, this will it cumbersome to work with..  These aren't big changes and will help make it more flexible

**Comment by Tamburasca** [comment]
will we have a config file for each unit? 
yes, consider that each device may have a different firm ware. First, I want to see a 80% solution that is working, not a 120% solution that isn't. Usually specs are defined before development, not thereafter.

You can clone the entire repo locally and run the reader/writer or even better run the Web API (outside Docker) and adjust the configs to your liking for testing.

BTW you updated a CryoMech config that will not work.

**Comment by RonanHiggins** [comment]
Just so we're clear, each compressor and rack heat exchange will have it's own config file? so that 16 compressor configs and 8 heat exhangers config files? with the only difference being the IP address? 

We will test CryoMech config when we have the unit in place, I wanted to record those 32bit updates that were missing from the original config file.. the rest we can test when we have the machine online.

**Comment by Tamburasca** [comment]
In an earlier release of the MODBUS design originally I had two files: one for the mapping of registers (for each device class) and the other for the connection details of each device. Upon your request I merged those into one.

**Comment by Tamburasca** [comment]
SOFIA is not CCAT. MODBUSs' prime customer is the HK. Here we want real deivce names not IPs (particularly, when selecting in Swagger OpenAPI)

**Comment by Tamburasca** [comment]
As a note aside. the upper register in the configs is obsolete, as the width is determined by the function. e.g. a 64bit float will automatically cover 4 registers now (latest release). The sole exception is with strings that cover >1 register

**Comment by RonanHiggins** [comment]
How will the FAT work then? I will need to continuously change a config file with a fixed filename? if I want to read one register say 20 bytes in how would that work?

**Comment by Tamburasca** [comment]
In 
imc096_cpa_series_digital_panel_user_manual_.pdf 
I read the following lines. 

...
The first two 'Input' registers and the only 'Holding' register are 16 bit integer registers
and the rest of the input registers are in 32bit floating point format. The PLC code is
written in Structured Text and the data stored is a REAL value. This means two Input
registers are used to hold the value and the bytes will have to be rearranged before
CPA Digital Panel User Manualconverting them to floating format on the system.
...

Hence, we need to investigate the first two Input registers. Also
a matter to investigate is word and byte endiannesses.
