### ISSUE TITLE
develop a setup.py for this repo for easier install

### ISSUE THREAD

**Issue by RonanHiggins** [ccatp/MODBUS#7]
You should be able to pip install this library, I can see use outside of the docker/REST API approach.
The CHAI use may want to install this locally and import the library.
Using the setup.py could be use to install the library directly from the github
@Tamburasca @nolta

**Comment by RonanHiggins** [comment]
using this to track the development branch 7

**Comment by Tamburasca** [comment]
Take into account that we got two parallel developments synch/async. All is still in the flow and yet to be decided

**Comment by Tamburasca** [comment]
Setting PYTHONPATH is done in the helper routines read/write

**Comment by Tamburasca** [comment]
setup.py and optional config file is implemented in branch qa now
