### ISSUE TITLE
Misleading version in version.py

### ISSUE THREAD

**Issue by rschaaf-aifa** [ccatp/MODBUS#9]
The version as given in `version.py` is the commit number of the previous commit. This is highly misleading. `version.py` should either contain the commit number of the current commit or a completely different version number. Alternatively, the file should be removed.

**Comment by Tamburasca** [comment]
as agreed last SW conference this year we agreed on the following pre-commit in hooks:

ralf:~/pycharm-projects/ccatp/MODBUS/.git/hooks$ cat pre-commit
#!/bin/sh
 
GIT_VERSION=$(git describe --always)
 
if [ -n "$GIT_VERSION" ]; then
    echo "__version__ = '$GIT_VERSION'" > ./version.py
    git add ./version.py
fi

**Comment by rschaaf-aifa** [comment]
This does not seem to work correctly, s. screenshot from https://github.com/ccatp/MODBUS/blob/qa/version.py
![Bildschirmfoto 2023-08-11 um 14 33 14](https://github.com/ccatp/MODBUS/assets/3543367/98204645-0053-4788-a9ec-b4e8085496d9)

**Comment by Tamburasca** [comment]
sorry I only adopted the code in the programmer's manual. Who put it there, anyways?

Then we should revise the manual and I get rid of the pre-commit hook

**Comment by Tamburasca** [comment]
Next commit it's gonna be gone

**Comment by Tamburasca** [comment]
Suppose the issue is solved
